# Global variables
NUM_OF_CARDS_EACH_COLOUR = 13
NUM_OF_COLOURS = 5
ALL_COLOURS = ("Red", "Green", "Blue", "Yellow", "Pink")
COLOURS = ALL_COLOURS
NUM_OF_JOKER_CARDS = 2
NUM_OF_IDENTICAL_CARDS = 2
MAX_ROUND = 10

NUM_OF_AI_PLAYERS = 0
NUM_OF_HUMAN_PLAYERS = 4

# Variables for GameEngine
REGENERATE_IMAGE = True

# Variables for GameUI
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
BACKGROUND_COLOUR = "aquamarine4"
CAPTION = "Rummikub"

CARD_WIDTH = 30
CARD_HEIGHT = 50

GRID_WIDTH = CARD_WIDTH * 13 + 10
GRID_HEIGHT = CARD_HEIGHT + 10

HANDS_REGION = 100

# board region
# BOARD_WIDTH = SCREEN_WIDTH - 2 * HANDS_REGION
# BOARD_HEIGHT = SCREEN_HEIGHT - 2 * HANDS_REGION
BOARD_WIDTH = GRID_WIDTH * 2
BOARD_HEIGHT = GRID_HEIGHT * 8
