# Global variables
NUM_OF_CARDS_EACH_COLOUR = 13
NUM_OF_COLOURS = 5
ALL_COLOURS = ("Red", "Green", "Blue", "Yellow", "Pink")
COLOURS = ALL_COLOURS
NUM_OF_JOKER_CARDS = 2
NUM_OF_IDENTICAL_CARDS = 2
MAX_ROUND = 10
MAX_TIME = 100

NUM_OF_AI_PLAYERS = 0
NUM_OF_HUMAN_PLAYERS = 4

# Variables for GameEngine
REGENERATE_IMAGE = True

# Variables for GameUI
# ALL OTHERS ARE DEPENDENT ON THESE TWO
SET_SCREEN_WIDTH = 1440
SET_SCREEN_HEIGHT = SET_SCREEN_WIDTH * 9 // 16


# Variables for GameUI
SCREEN_WIDTH = SET_SCREEN_WIDTH
SCREEN_HEIGHT = SET_SCREEN_HEIGHT
BACKGROUND_COLOUR = "#009BC1"
CAPTION = "Rummikub"


#  you can change the SCALE to make the cards bigger or smaller
SCALE = 32
CARD_WIDTH = SCREEN_WIDTH // SCALE
CARD_HEIGHT = CARD_WIDTH * 955 // 684

GAP = CARD_WIDTH//5

# each grid cell region
GRID_WIDTH = CARD_WIDTH * 8 + 9 * GAP
GRID_HEIGHT = CARD_HEIGHT + 2 * GAP


# board region
BOARD_WIDTH = GRID_WIDTH * 2
BOARD_HEIGHT = GRID_HEIGHT * 8 

# hands region
HEIGHT_1_ROW = CARD_HEIGHT + 2 * GAP
WIDTH_2_COLUMNS = CARD_WIDTH * 2 + 3 * GAP
P1_HANDS_REGION = (WIDTH_2_COLUMNS, HEIGHT_1_ROW + BOARD_HEIGHT, BOARD_WIDTH, HEIGHT_1_ROW)
P3_HANDS_REGION = (WIDTH_2_COLUMNS, 0, BOARD_WIDTH, HEIGHT_1_ROW)

P2_HANDS_REGION = (0, HEIGHT_1_ROW, WIDTH_2_COLUMNS, BOARD_HEIGHT)
P4_HANDS_REGION = (WIDTH_2_COLUMNS + BOARD_WIDTH, HEIGHT_1_ROW, WIDTH_2_COLUMNS, BOARD_HEIGHT)


# button region
BUTTON_X = WIDTH_2_COLUMNS * 2 + BOARD_WIDTH + 2 * GAP
BUTTON_Y = 2 * GAP
BUTTON_GAP = CARD_HEIGHT + 2 * GAP
BUTTON_WIDTH = CARD_WIDTH * 6
BUTTON_HEIGHT = CARD_HEIGHT

END_TURN_BUTTON_REGION = (BUTTON_X, BUTTON_Y, BUTTON_WIDTH, BUTTON_HEIGHT)
PLAY_FOR_ME_BUTTON_REGION = (BUTTON_X, BUTTON_Y + BUTTON_GAP, BUTTON_WIDTH, BUTTON_HEIGHT)
FLIP_ALL_CARDS_BUTTON_REGION = (BUTTON_X, BUTTON_Y + 2 * BUTTON_GAP, BUTTON_WIDTH, BUTTON_HEIGHT)
DRAW_BUTTON_REGION = (BUTTON_X, BUTTON_Y + 3 * BUTTON_GAP, BUTTON_WIDTH, BUTTON_HEIGHT)

# draw cards region
DRAW_CARDS_REGION = (BUTTON_X, BUTTON_Y + 4 * BUTTON_GAP, 2 * CARD_WIDTH + 3 * GAP, CARD_HEIGHT + 2 * GAP)

# notification region
NOTIFICATION_REGION_1 = (BUTTON_X + GAP, 6 * BUTTON_GAP, BUTTON_WIDTH, BUTTON_HEIGHT)
NOTIFICATION_REGION_2 = (BUTTON_X + GAP, 6 * BUTTON_GAP + 4 * GAP, BUTTON_WIDTH, BUTTON_HEIGHT)
NOTIFICATION_REGION_3 = (BUTTON_X + GAP, 6 * BUTTON_GAP + 8 * GAP, BUTTON_WIDTH, BUTTON_HEIGHT)