# Global variables
NUM_OF_CARDS_EACH_COLOUR = 13
NUM_OF_COLOURS = 5
ALL_COLOURS = ("Red", "Green", "Blue", "Yellow", "Pink")
COLOURS = ALL_COLOURS
NUM_OF_JOKER_CARDS = 2
NUM_OF_IDENTICAL_CARDS = 2

NUM_OF_AI_PLAYERS = 0
NUM_OF_HUMAN_PLAYERS = 4

# Variables for GameEngine
REGENERATE_IMAGE = False

# Variables for GameUI
SCREEN_WIDTH = 1900
SCREEN_HEIGHT = 1200
BACKGROUND_COLOUR = "aquamarine4"
CAPTION = "Rummikub"

CARD_WIDTH = 40
CARD_HEIGHT = 60

GRID_WIDTH = 500
GRID_HEIGHT = 80

HANDS_REGION = 200

# board region
BOARD_WIDTH = SCREEN_WIDTH - 2 * HANDS_REGION
BOARD_HEIGHT = SCREEN_HEIGHT - 2 * HANDS_REGION